# up container: docker compose up -d
# stop all container: docker compose stop

version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      -5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
